# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1368, 782)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(840, 540, 521, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 521, 191))
        self.graphicsView.setObjectName("graphicsView")
        self.glyph_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.glyph_view.setGeometry(QtCore.QRect(840, 10, 521, 491))
        self.glyph_view.setObjectName("glyph_view")
        self.gober = QtWidgets.QLabel(self.centralwidget)
        self.gober.setGeometry(QtCore.QRect(9, 597, 30, 151))
        self.gober.setText("")
        self.gober.setObjectName("gober")
        self.social = QtWidgets.QLabel(self.centralwidget)
        self.social.setGeometry(QtCore.QRect(9, 460, 30, 150))
        self.social.setText("")
        self.social.setObjectName("social")
        self.econo = QtWidgets.QLabel(self.centralwidget)
        self.econo.setGeometry(QtCore.QRect(9, 360, 30, 111))
        self.econo.setText("")
        self.econo.setObjectName("econo")
        self.ecolo = QtWidgets.QLabel(self.centralwidget)
        self.ecolo.setGeometry(QtCore.QRect(9, 115, 30, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ecolo.setFont(font)
        self.ecolo.setText("")
        self.ecolo.setObjectName("ecolo")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 12, 781, 772))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_0 = QtWidgets.QLabel(self.layoutWidget)
        self.label_0.setMinimumSize(QtCore.QSize(565, 0))
        self.label_0.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_0.setObjectName("label_0")
        self.horizontalLayout.addWidget(self.label_0)
        self.lcdNumber_0 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_0.setMaximumSize(QtCore.QSize(41, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_0.setFont(font)
        self.lcdNumber_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_0.setLineWidth(1)
        self.lcdNumber_0.setNumDigits(3)
        self.lcdNumber_0.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_0.setObjectName("lcdNumber_0")
        self.horizontalLayout.addWidget(self.lcdNumber_0)
        self.slider_0 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_0.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_0.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_0.setOrientation(QtCore.Qt.Horizontal)
        self.slider_0.setObjectName("slider_0")
        self.horizontalLayout.addWidget(self.slider_0)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_1.setMinimumSize(QtCore.QSize(565, 0))
        self.label_1.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_2.addWidget(self.label_1)
        self.lcdNumber_1 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_1.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_1.setNumDigits(3)
        self.lcdNumber_1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_1.setObjectName("lcdNumber_1")
        self.horizontalLayout_2.addWidget(self.lcdNumber_1)
        self.slider_1 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_1.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_1.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_1.setObjectName("slider_1")
        self.horizontalLayout_2.addWidget(self.slider_1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(565, 0))
        self.label_2.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_2.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_2.setNumDigits(3)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout_3.addWidget(self.lcdNumber_2)
        self.slider_2 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_2.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_2.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_2.setObjectName("slider_2")
        self.horizontalLayout_3.addWidget(self.slider_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(565, 0))
        self.label_3.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_3.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_3.setNumDigits(3)
        self.lcdNumber_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.horizontalLayout_4.addWidget(self.lcdNumber_3)
        self.slider_3 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_3.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_3.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_3.setObjectName("slider_3")
        self.horizontalLayout_4.addWidget(self.slider_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(565, 0))
        self.label_4.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_4.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_4.setNumDigits(3)
        self.lcdNumber_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.horizontalLayout_5.addWidget(self.lcdNumber_4)
        self.slider_4 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_4.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_4.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_4.setObjectName("slider_4")
        self.horizontalLayout_5.addWidget(self.slider_4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(565, 0))
        self.label_5.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_5.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_5.setNumDigits(3)
        self.lcdNumber_5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.horizontalLayout_6.addWidget(self.lcdNumber_5)
        self.slider_5 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_5.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_5.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_5.setOrientation(QtCore.Qt.Horizontal)
        self.slider_5.setObjectName("slider_5")
        self.horizontalLayout_6.addWidget(self.slider_5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(565, 0))
        self.label_6.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_6.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_6.setNumDigits(3)
        self.lcdNumber_6.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.horizontalLayout_7.addWidget(self.lcdNumber_6)
        self.slider_6 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_6.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_6.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_6.setOrientation(QtCore.Qt.Horizontal)
        self.slider_6.setObjectName("slider_6")
        self.horizontalLayout_7.addWidget(self.slider_6)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(565, 0))
        self.label_7.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_7.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_7.setNumDigits(3)
        self.lcdNumber_7.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.horizontalLayout_8.addWidget(self.lcdNumber_7)
        self.slider_7 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_7.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_7.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_7.setOrientation(QtCore.Qt.Horizontal)
        self.slider_7.setObjectName("slider_7")
        self.horizontalLayout_8.addWidget(self.slider_7)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(565, 0))
        self.label_8.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_8.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_8.setNumDigits(3)
        self.lcdNumber_8.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.horizontalLayout_9.addWidget(self.lcdNumber_8)
        self.slider_8 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_8.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_8.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_8.setOrientation(QtCore.Qt.Horizontal)
        self.slider_8.setObjectName("slider_8")
        self.horizontalLayout_9.addWidget(self.slider_8)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(565, 0))
        self.label_9.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_9.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_9.setNumDigits(3)
        self.lcdNumber_9.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.horizontalLayout_10.addWidget(self.lcdNumber_9)
        self.slider_9 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_9.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_9.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_9.setOrientation(QtCore.Qt.Horizontal)
        self.slider_9.setObjectName("slider_9")
        self.horizontalLayout_10.addWidget(self.slider_9)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.line_11 = QtWidgets.QFrame(self.layoutWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout.addWidget(self.line_11)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(565, 0))
        self.label_10.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_10.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_10.setNumDigits(3)
        self.lcdNumber_10.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.horizontalLayout_11.addWidget(self.lcdNumber_10)
        self.slider_10 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_10.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_10.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_10.setOrientation(QtCore.Qt.Horizontal)
        self.slider_10.setObjectName("slider_10")
        self.horizontalLayout_11.addWidget(self.slider_10)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(565, 0))
        self.label_11.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_11.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_11.setNumDigits(3)
        self.lcdNumber_11.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.horizontalLayout_12.addWidget(self.lcdNumber_11)
        self.slider_11 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_11.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_11.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_11.setOrientation(QtCore.Qt.Horizontal)
        self.slider_11.setObjectName("slider_11")
        self.horizontalLayout_12.addWidget(self.slider_11)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(565, 0))
        self.label_12.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.lcdNumber_12 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_12.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_12.setNumDigits(3)
        self.lcdNumber_12.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.horizontalLayout_13.addWidget(self.lcdNumber_12)
        self.slider_12 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_12.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_12.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_12.setOrientation(QtCore.Qt.Horizontal)
        self.slider_12.setObjectName("slider_12")
        self.horizontalLayout_13.addWidget(self.slider_12)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.line_12 = QtWidgets.QFrame(self.layoutWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout.addWidget(self.line_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(565, 0))
        self.label_13.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.lcdNumber_13 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_13.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_13.setNumDigits(3)
        self.lcdNumber_13.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.horizontalLayout_14.addWidget(self.lcdNumber_13)
        self.slider_13 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_13.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_13.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_13.setOrientation(QtCore.Qt.Horizontal)
        self.slider_13.setObjectName("slider_13")
        self.horizontalLayout_14.addWidget(self.slider_13)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(565, 0))
        self.label_14.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        self.lcdNumber_14 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_14.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_14.setNumDigits(3)
        self.lcdNumber_14.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.horizontalLayout_15.addWidget(self.lcdNumber_14)
        self.slider_14 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_14.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_14.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_14.setOrientation(QtCore.Qt.Horizontal)
        self.slider_14.setObjectName("slider_14")
        self.horizontalLayout_15.addWidget(self.slider_14)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(565, 0))
        self.label_15.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.lcdNumber_15 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_15.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_15.setNumDigits(3)
        self.lcdNumber_15.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.horizontalLayout_16.addWidget(self.lcdNumber_15)
        self.slider_15 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_15.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_15.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_15.setOrientation(QtCore.Qt.Horizontal)
        self.slider_15.setObjectName("slider_15")
        self.horizontalLayout_16.addWidget(self.slider_15)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.line_13 = QtWidgets.QFrame(self.layoutWidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout.addWidget(self.line_13)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(565, 0))
        self.label_16.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.lcdNumber_16 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_16.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_16.setNumDigits(3)
        self.lcdNumber_16.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.horizontalLayout_17.addWidget(self.lcdNumber_16)
        self.slider_16 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_16.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_16.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_16.setOrientation(QtCore.Qt.Horizontal)
        self.slider_16.setObjectName("slider_16")
        self.horizontalLayout_17.addWidget(self.slider_16)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setMinimumSize(QtCore.QSize(565, 0))
        self.label_17.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_18.addWidget(self.label_17)
        self.lcdNumber_17 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_17.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_17.setNumDigits(3)
        self.lcdNumber_17.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.horizontalLayout_18.addWidget(self.lcdNumber_17)
        self.slider_17 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_17.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_17.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_17.setOrientation(QtCore.Qt.Horizontal)
        self.slider_17.setObjectName("slider_17")
        self.horizontalLayout_18.addWidget(self.slider_17)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setMinimumSize(QtCore.QSize(565, 0))
        self.label_18.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.lcdNumber_18 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_18.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_18.setNumDigits(3)
        self.lcdNumber_18.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.horizontalLayout_19.addWidget(self.lcdNumber_18)
        self.slider_18 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_18.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_18.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_18.setOrientation(QtCore.Qt.Horizontal)
        self.slider_18.setObjectName("slider_18")
        self.horizontalLayout_19.addWidget(self.slider_18)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setMinimumSize(QtCore.QSize(565, 0))
        self.label_19.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_20.addWidget(self.label_19)
        self.lcdNumber_19 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_19.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_19.setNumDigits(3)
        self.lcdNumber_19.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.horizontalLayout_20.addWidget(self.lcdNumber_19)
        self.slider_19 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_19.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_19.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_19.setOrientation(QtCore.Qt.Horizontal)
        self.slider_19.setObjectName("slider_19")
        self.horizontalLayout_20.addWidget(self.slider_19)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setMinimumSize(QtCore.QSize(565, 0))
        self.label_20.setMaximumSize(QtCore.QSize(565, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.lcdNumber_20 = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_20.setMaximumSize(QtCore.QSize(41, 16777215))
        self.lcdNumber_20.setNumDigits(3)
        self.lcdNumber_20.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.horizontalLayout_21.addWidget(self.lcdNumber_20)
        self.slider_20 = QtWidgets.QSlider(self.layoutWidget)
        self.slider_20.setMinimumSize(QtCore.QSize(135, 0))
        self.slider_20.setMaximumSize(QtCore.QSize(135, 16777215))
        self.slider_20.setOrientation(QtCore.Qt.Horizontal)
        self.slider_20.setObjectName("slider_20")
        self.horizontalLayout_21.addWidget(self.slider_20)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.introButton = QtWidgets.QPushButton(self.centralwidget)
        self.introButton.setGeometry(QtCore.QRect(0, 1, 1368, 779))
        self.introButton.setText("")
        self.introButton.setObjectName("introButton")
        self.inicioButton = QtWidgets.QPushButton(self.centralwidget)
        self.inicioButton.setGeometry(QtCore.QRect(840, 733, 110, 32))
        self.inicioButton.setObjectName("inicioButton")
        self.creditosButton = QtWidgets.QPushButton(self.centralwidget)
        self.creditosButton.setGeometry(QtCore.QRect(1240, 733, 110, 32))
        self.creditosButton.setObjectName("creditosButton")
        self.loadExcel = QtWidgets.QPushButton(self.centralwidget)
        self.loadExcel.setGeometry(QtCore.QRect(1110, 733, 111, 32))
        self.loadExcel.setObjectName("loadExcel")
        self.guardarButton = QtWidgets.QPushButton(self.centralwidget)
        self.guardarButton.setGeometry(QtCore.QRect(980, 733, 110, 32))
        self.guardarButton.setObjectName("guardarButton")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(840, 505, 51, 32))
        self.back.setObjectName("back")
        self.back.raise_()
        self.frame.raise_()
        self.glyph_view.raise_()
        self.gober.raise_()
        self.social.raise_()
        self.econo.raise_()
        self.ecolo.raise_()
        self.layoutWidget.raise_()
        self.introButton.raise_()
        self.inicioButton.raise_()
        self.creditosButton.raise_()
        self.loadExcel.raise_()
        self.guardarButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1368, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sustentabilidad Urbana"))
        self.label_0.setText(_translate("MainWindow", "TextLabel"))
        self.label_1.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "TextLabel"))
        self.inicioButton.setText(_translate("MainWindow", "Inicio"))
        self.creditosButton.setText(_translate("MainWindow", "Créditos"))
        self.loadExcel.setText(_translate("MainWindow", "Cargar"))
        self.guardarButton.setText(_translate("MainWindow", "Guardar"))
        self.back.setText(_translate("MainWindow", "<<"))

