# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1413, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(810, 540, 581, 171))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 581, 171))
        self.graphicsView.setObjectName("graphicsView")
        self.glyph_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.glyph_view.setGeometry(QtCore.QRect(810, 10, 581, 521))
        self.glyph_view.setObjectName("glyph_view")
        self.gober = QtWidgets.QLabel(self.centralwidget)
        self.gober.setGeometry(QtCore.QRect(10, 570, 71, 151))
        self.gober.setObjectName("gober")
        self.social = QtWidgets.QLabel(self.centralwidget)
        self.social.setGeometry(QtCore.QRect(0, 460, 81, 101))
        self.social.setObjectName("social")
        self.econo = QtWidgets.QLabel(self.centralwidget)
        self.econo.setGeometry(QtCore.QRect(10, 340, 71, 111))
        self.econo.setObjectName("econo")
        self.ecolo = QtWidgets.QLabel(self.centralwidget)
        self.ecolo.setGeometry(QtCore.QRect(20, 110, 61, 141))
        self.ecolo.setObjectName("ecolo")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(600, 10, 201, 731))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_8 = QtWidgets.QFrame(self.widget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.slider_0 = QtWidgets.QSlider(self.widget)
        self.slider_0.setOrientation(QtCore.Qt.Horizontal)
        self.slider_0.setObjectName("slider_0")
        self.verticalLayout.addWidget(self.slider_0)
        self.slider_1 = QtWidgets.QSlider(self.widget)
        self.slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_1.setObjectName("slider_1")
        self.verticalLayout.addWidget(self.slider_1)
        self.slider_2 = QtWidgets.QSlider(self.widget)
        self.slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_2.setObjectName("slider_2")
        self.verticalLayout.addWidget(self.slider_2)
        self.slider_3 = QtWidgets.QSlider(self.widget)
        self.slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_3.setObjectName("slider_3")
        self.verticalLayout.addWidget(self.slider_3)
        self.slider_4 = QtWidgets.QSlider(self.widget)
        self.slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_4.setObjectName("slider_4")
        self.verticalLayout.addWidget(self.slider_4)
        self.slider_5 = QtWidgets.QSlider(self.widget)
        self.slider_5.setOrientation(QtCore.Qt.Horizontal)
        self.slider_5.setObjectName("slider_5")
        self.verticalLayout.addWidget(self.slider_5)
        self.slider_6 = QtWidgets.QSlider(self.widget)
        self.slider_6.setOrientation(QtCore.Qt.Horizontal)
        self.slider_6.setObjectName("slider_6")
        self.verticalLayout.addWidget(self.slider_6)
        self.slider_7 = QtWidgets.QSlider(self.widget)
        self.slider_7.setOrientation(QtCore.Qt.Horizontal)
        self.slider_7.setObjectName("slider_7")
        self.verticalLayout.addWidget(self.slider_7)
        self.slider_8 = QtWidgets.QSlider(self.widget)
        self.slider_8.setOrientation(QtCore.Qt.Horizontal)
        self.slider_8.setObjectName("slider_8")
        self.verticalLayout.addWidget(self.slider_8)
        self.slider_9 = QtWidgets.QSlider(self.widget)
        self.slider_9.setOrientation(QtCore.Qt.Horizontal)
        self.slider_9.setObjectName("slider_9")
        self.verticalLayout.addWidget(self.slider_9)
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.slider_10 = QtWidgets.QSlider(self.widget)
        self.slider_10.setOrientation(QtCore.Qt.Horizontal)
        self.slider_10.setObjectName("slider_10")
        self.verticalLayout.addWidget(self.slider_10)
        self.slider_11 = QtWidgets.QSlider(self.widget)
        self.slider_11.setOrientation(QtCore.Qt.Horizontal)
        self.slider_11.setObjectName("slider_11")
        self.verticalLayout.addWidget(self.slider_11)
        self.slider_12 = QtWidgets.QSlider(self.widget)
        self.slider_12.setOrientation(QtCore.Qt.Horizontal)
        self.slider_12.setObjectName("slider_12")
        self.verticalLayout.addWidget(self.slider_12)
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.slider_13 = QtWidgets.QSlider(self.widget)
        self.slider_13.setOrientation(QtCore.Qt.Horizontal)
        self.slider_13.setObjectName("slider_13")
        self.verticalLayout.addWidget(self.slider_13)
        self.slider_14 = QtWidgets.QSlider(self.widget)
        self.slider_14.setOrientation(QtCore.Qt.Horizontal)
        self.slider_14.setObjectName("slider_14")
        self.verticalLayout.addWidget(self.slider_14)
        self.slider_15 = QtWidgets.QSlider(self.widget)
        self.slider_15.setOrientation(QtCore.Qt.Horizontal)
        self.slider_15.setObjectName("slider_15")
        self.verticalLayout.addWidget(self.slider_15)
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.slider_16 = QtWidgets.QSlider(self.widget)
        self.slider_16.setOrientation(QtCore.Qt.Horizontal)
        self.slider_16.setObjectName("slider_16")
        self.verticalLayout.addWidget(self.slider_16)
        self.slider_17 = QtWidgets.QSlider(self.widget)
        self.slider_17.setOrientation(QtCore.Qt.Horizontal)
        self.slider_17.setObjectName("slider_17")
        self.verticalLayout.addWidget(self.slider_17)
        self.slider_18 = QtWidgets.QSlider(self.widget)
        self.slider_18.setOrientation(QtCore.Qt.Horizontal)
        self.slider_18.setObjectName("slider_18")
        self.verticalLayout.addWidget(self.slider_18)
        self.slider_19 = QtWidgets.QSlider(self.widget)
        self.slider_19.setOrientation(QtCore.Qt.Horizontal)
        self.slider_19.setObjectName("slider_19")
        self.verticalLayout.addWidget(self.slider_19)
        self.slider_20 = QtWidgets.QSlider(self.widget)
        self.slider_20.setOrientation(QtCore.Qt.Horizontal)
        self.slider_20.setObjectName("slider_20")
        self.verticalLayout.addWidget(self.slider_20)
        self.line_10 = QtWidgets.QFrame(self.widget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout.addWidget(self.line_10)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(90, 10, 511, 731))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_7 = QtWidgets.QFrame(self.widget1)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.label_0 = QtWidgets.QLabel(self.widget1)
        self.label_0.setObjectName("label_0")
        self.verticalLayout_2.addWidget(self.label_0)
        self.label_1 = QtWidgets.QLabel(self.widget1)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_2.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget1)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.line = QtWidgets.QFrame(self.widget1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_10 = QtWidgets.QLabel(self.widget1)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget1)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget1)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.line_2 = QtWidgets.QFrame(self.widget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_13 = QtWidgets.QLabel(self.widget1)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget1)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.widget1)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.line_3 = QtWidgets.QFrame(self.widget1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.label_16 = QtWidgets.QLabel(self.widget1)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.widget1)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.widget1)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.widget1)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.widget1)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.line_9 = QtWidgets.QFrame(self.widget1)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_2.addWidget(self.line_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1413, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gober.setText(_translate("MainWindow", "Gobernanza"))
        self.social.setText(_translate("MainWindow", "Socio-cultural"))
        self.econo.setText(_translate("MainWindow", "Económica"))
        self.ecolo.setText(_translate("MainWindow", "Ecologica"))
        self.label_0.setText(_translate("MainWindow", "TextLabel"))
        self.label_1.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "TextLabel"))

