# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 781, 311))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 781, 311))
        self.graphicsView.setObjectName("graphicsView")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 360, 791, 171))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalSlider_1 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_1.setObjectName("verticalSlider_1")
        self.horizontalLayout.addWidget(self.verticalSlider_1)
        self.verticalSlider_2 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.horizontalLayout.addWidget(self.verticalSlider_2)
        self.verticalSlider_3 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.horizontalLayout.addWidget(self.verticalSlider_3)
        self.verticalSlider_4 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setObjectName("verticalSlider_4")
        self.horizontalLayout.addWidget(self.verticalSlider_4)
        self.verticalSlider_5 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setObjectName("verticalSlider_5")
        self.horizontalLayout.addWidget(self.verticalSlider_5)
        self.verticalSlider_6 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setObjectName("verticalSlider_6")
        self.horizontalLayout.addWidget(self.verticalSlider_6)
        self.verticalSlider_7 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_7.setObjectName("verticalSlider_7")
        self.horizontalLayout.addWidget(self.verticalSlider_7)
        self.verticalSlider_8 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_8.setObjectName("verticalSlider_8")
        self.horizontalLayout.addWidget(self.verticalSlider_8)
        self.verticalSlider_9 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_9.setObjectName("verticalSlider_9")
        self.horizontalLayout.addWidget(self.verticalSlider_9)
        self.verticalSlider_10 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_10.setObjectName("verticalSlider_10")
        self.horizontalLayout.addWidget(self.verticalSlider_10)
        self.verticalSlider_11 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_11.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_11.setObjectName("verticalSlider_11")
        self.horizontalLayout.addWidget(self.verticalSlider_11)
        self.verticalSlider_12 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_12.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_12.setObjectName("verticalSlider_12")
        self.horizontalLayout.addWidget(self.verticalSlider_12)
        self.verticalSlider_13 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_13.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_13.setObjectName("verticalSlider_13")
        self.horizontalLayout.addWidget(self.verticalSlider_13)
        self.verticalSlider_14 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_14.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_14.setObjectName("verticalSlider_14")
        self.horizontalLayout.addWidget(self.verticalSlider_14)
        self.verticalSlider_15 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_15.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_15.setObjectName("verticalSlider_15")
        self.horizontalLayout.addWidget(self.verticalSlider_15)
        self.verticalSlider_16 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_16.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_16.setObjectName("verticalSlider_16")
        self.horizontalLayout.addWidget(self.verticalSlider_16)
        self.verticalSlider_17 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_17.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_17.setObjectName("verticalSlider_17")
        self.horizontalLayout.addWidget(self.verticalSlider_17)
        self.verticalSlider_18 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_18.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_18.setObjectName("verticalSlider_18")
        self.horizontalLayout.addWidget(self.verticalSlider_18)
        self.verticalSlider_19 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_19.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_19.setObjectName("verticalSlider_19")
        self.horizontalLayout.addWidget(self.verticalSlider_19)
        self.verticalSlider_20 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_20.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_20.setObjectName("verticalSlider_20")
        self.horizontalLayout.addWidget(self.verticalSlider_20)
        self.verticalSlider_21 = QtWidgets.QSlider(self.widget)
        self.verticalSlider_21.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_21.setObjectName("verticalSlider_21")
        self.horizontalLayout.addWidget(self.verticalSlider_21)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

