["Ordenamiento territorial y planeación urbana sustentable",
"Edificaciones sustentables (Ecotecnias, diseño y materiales sustentables)",
"Industria limpia (produccion y circulacion sustentable)",
"Movilidad sustentable",
"Eficiencia energética y fomento a las energías renovables",
"Infraestructura verde-azul para la adaptacion al cambio climático",
"Conservación ambiental y adaptacion urbana basada en ecosistemas",
"Mitigacion de gases efecto invernadero y mejora de la calidad del aire",
"Gestión sustentable de residuos y cogeneración de energía",
"Fomento a la resiliencia urbana",
"Economía circular y mercados locales-regionales",
"Reducción de la pobreza y de la vulnerabilidad al cambio climático",
"Financiamiento para la sustentabilidad urbana",
"Acciones de educación para el cambio climático y difusión para la sustentabilidad",
"Participación social en el avance hacia la sustentabilidad, incluyente y justa",
"Mejoramiento de la salud pública",
"Gestión de riesgo de desastres y reducción de la vulnerabilidad al cambio climático",
"Presupuesto climático y seguros contra riesgos hidro-meteorológicos",
"Combate a la corrupción y rendición de cuentas",
"Construcción de capacidades para sustentabilidad urbana con perspectiva de género",
"Fortalecimiento de la gobernanza del cambio climático"]
